import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';

import { Save } from 'lucide-react';
import { uniqueNamesGenerator, adjectives, animals } from 'unique-names-generator';

import { styled } from '@/helpers/utils';
import { useModal } from '@/hooks/use-modal';
import { Button } from '@/ui/button';
import { Input } from '@/ui/input';
import { Label } from '@/ui/label';

import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/ui/dialog';

const Separator = styled('div', 'flex-1');

const getRandomName = () => {
    return uniqueNamesGenerator({
        dictionaries: [adjectives, animals],
        length: 2,
        separator: ' ',
        style: 'capital',
    });
};

export const CreateCollectionDialog = () => {
    const { t } = useTranslation();
    const { isOpen, close, props } = useModal('create-collection');
    const { onCreate } = props;

    const [placeholder, setPlaceholder] = useState('');
    const [name, setName] = useState('');

    const canSubmit = name.trim() !== '';

    useEffect(() => {
        if (isOpen) {
            setName('');
            setPlaceholder(getRandomName());
        }
    }, [isOpen]);

    const handleCreate = ev => {
        ev.preventDefault();
        if (!canSubmit) return;
        onCreate?.({ name });
        close();
    };

    const handleAutoGenerated = () => {
        onCreate?.({ name: placeholder });
        close();
    };

    return (
        <Dialog open={isOpen} onOpenChange={v => !v && close()}>
            <DialogContent className='sm:max-w-md'>
                <form className='flex flex-col gap-2' onSubmit={handleCreate}>
                    <DialogHeader>
                        <DialogTitle>
                            {t('collections.dialogs.create-collection.title')}
                        </DialogTitle>
                        <DialogDescription>
                            {t('collections.dialogs.create-collection.description')}
                        </DialogDescription>
                    </DialogHeader>

                    <div className='flex items-center space-x-2'>
                        <div className='grid flex-1 gap-2'>
                            <Label htmlFor='group-name' className='sr-only'>
                                {t('collections.dialogs.create-collection.labels.name')}
                            </Label>
                            <Input
                                id='group-name'
                                name='group-name'
                                autoComplete='off'
                                placeholder={placeholder}
                                value={name}
                                onChange={ev => setName(ev.target.value)}
                            />
                        </div>
                    </div>

                    <DialogFooter className='sm:justify-start'>
                        <Button type='button' variant='secondary' onClick={handleAutoGenerated}>
                            {t('collections.dialogs.create-collection.labels.auto-name')}
                        </Button>

                        <Separator />

                        <Button type='button' variant='secondary' onClick={close}>
                            {t('collections.dialogs.create-collection.labels.cancel')}
                        </Button>

                        <Button type='submit' disabled={!canSubmit}>
                            <Save /> {t('collections.dialogs.create-collection.labels.save')}
                        </Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    );
};
